name: CI/CD Pipeline

# Trigger the pipeline on push or pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up the environment (if necessary, e.g., for C/C++, Python, Go, etc.)
      - name: Install build dependencies
        run: sudo apt-get install -y build-essential  # Adjust this to install required build tools

      # Step 3: Build the project using `make build`
      - name: Build the project
        run: make build

  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code again
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install testing tools (if needed)
      - name: Install pipe (or other testing dependencies)
        run: sudo apt-get install -y pipe  # Adjust this to install `pipe` or any other required tools

      # Step 3: Run tests using `pipe test`
      - name: Run tests
        run: pipe test
