name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Step 3: Install Python dependencies including Selenium
      - name: Install Selenium
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          
      # Step 4: Run tests using Selenium
      - name: Run tests
        run: python -m unittest discover  # Adjust this to your testing framework
